### PR TITLE
Minimize it

### PR DESCRIPTION
**Pull request by webwurst**
@zyndiecate @puja108

### CODE REVIEW

**Comment by webwurst** [comment]
Someone out there for a "IIWFYLGTM"? ,D

**Comment by marians** [comment]
IALI - I Am Loving It™

**Comment by puja108** [comment]
Awesome! Just now I'm getting the TLD error again

**Comment by zyndiecate** [comment]
I would like the testsuite to succeed using this. I have no idea what libraries are supported in the scratch image.

**Comment by webwurst** [comment]
@zyndiecate show me the way to your testsuite and i'll show you the secret ingredients of `scratch`. deal? ,D

**Comment by webwurst** [comment]
@puja108 I've added the ca-certificates from alpine:
```bash
$ sudo docker run --rm -ti alpine \
  sh -c "apk update >/dev/null \
    && apk add ca-certificates >/dev/null \
    && cat /etc/ssl/certs/ca-certificates.crt" \
  > ca-certificates.crt
```

**Comment by webwurst** [comment]
scratch image is just an empty image, see [Creating a simple base image using scratch](https://docs.docker.com/articles/baseimages/). so nothing magic with that.

**Comment by webwurst** [comment]
Instead of copying the ca-certificates from alpine we could use [mk-ca-bundle](https://github.com/bagder/curl/blob/master/lib/mk-ca-bundle.pl) [(manpage)](http://curl.haxx.se/docs/mk-ca-bundle.html) which brings us the [up-to-date](http://mxr.mozilla.org/mozilla-central/source/security/nss/lib/ckfw/builtins/certdata.txt) mozilla certificates.

Even better: We could provide a Docker image like [this one](https://registry.hub.docker.com/u/centurylink/ca-certs/dockerfile/) from CenturyLink and use it as a base image for our single-go-binary images.

**Comment by puja108** [comment]
I like the idea of a scratch + ca baseimage

**Pull request merged**
